import Head from 'next/head'
import styles from '../styles/Home.module.scss'

import { useState, useEffect, StrictMode } from 'react'
import Link from 'next/link'
import Image from 'next/image'

import Hero from '../components/layout/hero'
import PlayerData from '../components/getPlayerData'
import SetLeagueSettings from '../components/setLeagueSettings'
// import DashGraph from '../components/dashGraph' // To implement later - NON MVP

import Button from '@mui/material/Button';
import Modal from '@mui/material/Modal';
import Box from '@mui/material/Box';

import img_bmc from '../public/bmc_icon_black.png'


export default function Home(props) {
  const [lsID, setLSID] = useState('');
  const [colData, setColData] = useState({});
  const [posSettings, setPosSettings] = useState({});
  const [catSettings, setCatSettings] = useState({});

  const [lsModal, setLSModal] = useState(false);

  const handleOpen = () => setLSModal(true);
  const handleClose = () => setLSModal(false);

  const wait = delay => new Promise(resolve => setTimeout(resolve, delay));
  const scrollToDataTable = async () => {
    // await wait(500)
    document.getElementById("dataTableAnchor").scrollIntoView({behavior: "smooth"});
  }

  const getLSID = (lsID) => {
    setLSID(lsID);
    handleClose();
    scrollToDataTable();
  }

  const getColData = (colData) => {
    setColData(colData);
  }

  const getPosSettings = (posData) => {
    setPosSettings(posData)
  }

  const getCatSettings = (catData) => {
    setCatSettings(catData)
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Fantasy VORP - the Beta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <section className={styles.hero}>
          <div className={styles.contentContainer}>
              <h1>
                  Welcome to the <span className={styles.logoFont}>FantasyVORP.com</span> beta!
              </h1>
          </div>
        </section>


        <h2>NHL Fantasy VORP Data</h2>
        <Button 
          onClick={handleOpen} 
          variant="contained" 
          type="submit" 
          value="Submit"
          className="setLSbtn"
          >
            Input your League Settings
        </Button>
        <div id="dataTableAnchor"></div>
        {/* <StrictMode> */}
          <PlayerData lsID={lsID} colData={colData} posSettings={posSettings} catSettings={catSettings}/>
        {/* </StrictMode> */}

      </main>

      <Modal
        open={lsModal}
        onClose={handleClose}
        aria-labelledby="modal-modal-title"
        aria-describedby="modal-modal-description"
      >
        <Box>
          <SetLeagueSettings setLSModal={setLSModal} getLSID={getLSID} getColData={getColData} getPosSettings={getPosSettings} getCatSettings={getCatSettings}/>
        </Box>
      </Modal>

    </div>
  )
}