import Head from 'next/head'
import styles from '../styles/Home.module.scss'

import { useState, useEffect } from 'react'
import Link from 'next/link'

import Hero from '../components/layout/hero'
import PlayerData from '../components/getPlayerData'
import SetLeagueSettings from '../components/setLeagueSettings'
// import DashGraph from '../components/dashGraph' // To implement later - NON MVP

import Button from '@mui/material/Button';
import Modal from '@mui/material/Modal';
import Box from '@mui/material/Box';


export default function Home(props) {
  const [lsID, setLSID] = useState('');
  const [colData, setColData] = useState({});
  const [lsModal, setLSModal] = useState(false);

  const handleOpen = () => setLSModal(true);
  const handleClose = () => setLSModal(false);

  const getLSID = (lsID) => {
    setLSID(lsID);
  }

  const getColData = (colData) => {
    setColData(colData);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Fantasy VORP - the Beta</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <section className={styles.hero}>
          <div className={styles.contentContainer}>
              <h1>
                  Welcome to the <span className={styles.logoFont}>FantasyVORP.com</span> beta!
              </h1>

              <Button 
              onClick={handleOpen} 
              variant="contained" 
              type="submit" 
              value="Submit"
              >
                Input your League Settings
              </Button>
          </div>
      </section>

      <PlayerData lsID={lsID} colData={colData} />

      </main>

      <Modal
        open={lsModal}
        onClose={handleClose}
        aria-labelledby="modal-modal-title"
        aria-describedby="modal-modal-description"
      >
        <Box>
          <SetLeagueSettings setLSModal={setLSModal} getLSID={getLSID} getColData={getColData} />
        </Box>
      </Modal>
    </div>
  )
}