import Head from 'next/head'
import styles from '../styles/Home.module.scss'

import { useState, useEffect } from 'react'
import Link from 'next/link'

import MiniHero from '../components/layout/miniHero'
import RawData from '../components/getRawData'


export default function RawStats(props) {
  const [colData, setColData] = useState({});

  const wait = delay => new Promise(resolve => setTimeout(resolve, delay));
  const scrollToDataTable = async () => {
    await wait(500)
    document.getElementById("dataTableAnchor").scrollIntoView({behavior: "smooth"});
  }

  const getColData = (colData) => {
    setColData(colData);
  }

  let headlineText = "NHL Raw Stats"

  return (
    <div className={styles.container}>
        <Head>
        <title>Fantasy VORP - the Beta - Raw Stats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>

            <MiniHero headline={headlineText} />

            <div id="dataTableAnchor"></div>
            <RawData />

        </main>
    </div>
  )
}